[package]
name = "collect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["jemalloc"]

# TODO: mmap, memfd_create() ver

# bytes: use `bytes` crate for collecting instead of `std::vec`

# Use jemalloc instead of system malloc.
# Seems to reduce overall memory usage at the cost of a very small speed drop.
jemalloc = ["jemallocator"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip=true

[profile.symbols]
inherits="release"
#incremental=true
strip=false

[dependencies]
bytes = {version = "1.1.0", optional = true }
jemallocator = { version = "0.3.2", optional = true }
libc = "0.2.122"
